$(document).on('keyup', '#R_1', function (event) { var a = $('.function > .pole_for_func').length; if (a > 1) { $('#L_2').val($('#R_1').val()) } }); $(document).on('keyup', '#L_2', function (event) { $('#R_1').val($('#L_2').val()) });
$(document).on('keyup', '#R_2', function (event) { var a = $('.function > .pole_for_func').length; if (a > 2) { $('#L_3').val($('#R_2').val()) } }); $(document).on('keyup', '#L_3', function (event) { $('#R_2').val($('#L_3').val()) });
$(document).on('keyup', '#R_3', function (event) { var a = $('.function > .pole_for_func').length; if (a > 3) { $('#L_4').val($('#R_3').val()) } }); $(document).on('keyup', '#L_4', function (event) { $('#R_3').val($('#L_4').val()) });
$(document).on('keyup', '#R_4', function (event) { var a = $('.function > .pole_for_func').length; if (a > 4) { $('#L_5').val($('#R_4').val()) } }); $(document).on('keyup', '#L_5', function (event) { $('#R_4').val($('#L_5').val()) });
$(document).on('keyup', '#R_5', function (event) { var a = $('.function > .pole_for_func').length; if (a > 5) { $('#L_6').val($('#R_5').val()) } }); $(document).on('keyup', '#L_6', function (event) { $('#R_5').val($('#L_6').val()) });
$(document).on('keyup', '#R_6', function (event) { var a = $('.function > .pole_for_func').length; if (a > 6) { $('#L_7').val($('#R_6').val()) } }); $(document).on('keyup', '#L_7', function (event) { $('#R_6').val($('#L_7').val()) });
$(document).on('keyup', '#R_7', function (event) { var a = $('.function > .pole_for_func').length; if (a > 7) { $('#L_8').val($('#R_7').val()) } }); $(document).on('keyup', '#L_8', function (event) { $('#R_7').val($('#L_8').val()) });
$(document).on('keyup', '#R_8', function (event) { var a = $('.function > .pole_for_func').length; if (a > 8) { $('#L_9').val($('#R_8').val()) } }); $(document).on('keyup', '#L_9', function (event) { $('#R_8').val($('#L_9').val()) });
$(document).on('keyup', '#R_9', function (event) { var a = $('.function > .pole_for_func').length; if (a > 9) { $('#L_10').val($('#R_9').val()) } }); $(document).on('keyup', '#L_10', function (event) { $('#R_9').val($('#L_10').val()) });
$(document).on('keyup', '#R_10', function (event) { var a = $('.function > .pole_for_func').length; if (a > 10) { $('#L_11').val($('#R_10').val()) } }); $(document).on('keyup', '#L_11', function (event) { $('#R_10').val($('#L_11').val()) });
$(document).on('keyup', '#R_11', function (event) { var a = $('.function > .pole_for_func').length; if (a > 11) { $('#L_12').val($('#R_11').val()) } }); $(document).on('keyup', '#L_12', function (event) { $('#R_11').val($('#L_12').val()) });
$(document).on('keyup', '#R_12', function (event) { var a = $('.function > .pole_for_func').length; if (a > 12) { $('#L_13').val($('#R_12').val()) } }); $(document).on('keyup', '#L_13', function (event) { $('#R_12').val($('#L_13').val()) });
$(document).on('keyup', '#R_13', function (event) { var a = $('.function > .pole_for_func').length; if (a > 13) { $('#L_14').val($('#R_13').val()) } }); $(document).on('keyup', '#L_14', function (event) { $('#R_13').val($('#L_14').val()) });

$(document).on('keyup', '#R_1', function () { if (Number.parseFloat($('#R_1').val()) < Number.parseFloat($('#L_1').val())) { $('#1').css('borderColor', 'red'); } else { $('#1').css('borderColor', 'white'); } if (Number.parseFloat($('#R_2').val()) < Number.parseFloat($('#L_2').val())) { $('#2').css('borderColor', 'red'); } else { $('#2').css('borderColor', 'white'); } }); $(document).on('keyup', '#L_1', function () { if (Number.parseFloat($('#R_1').val()) < Number.parseFloat($('#L_1').val())) { $('#1').css('borderColor', 'red'); } else { $('#1').css('borderColor', 'white'); } if (Number.parseFloat($('#R_0').val()) < Number.parseFloat($('#L_0').val())) { $('#0').css('borderColor', 'red'); } else { $('#0').css('borderColor', 'white'); } });
$(document).on('keyup', '#R_2', function () { if (Number.parseFloat($('#R_2').val()) < Number.parseFloat($('#L_2').val())) { $('#2').css('borderColor', 'red'); } else { $('#2').css('borderColor', 'white'); } if (Number.parseFloat($('#R_3').val()) < Number.parseFloat($('#L_3').val())) { $('#3').css('borderColor', 'red'); } else { $('#3').css('borderColor', 'white'); } }); $(document).on('keyup', '#L_2', function () { if (Number.parseFloat($('#R_2').val()) < Number.parseFloat($('#L_2').val())) { $('#2').css('borderColor', 'red'); } else { $('#2').css('borderColor', 'white'); } if (Number.parseFloat($('#R_1').val()) < Number.parseFloat($('#L_1').val())) { $('#1').css('borderColor', 'red'); } else { $('#1').css('borderColor', 'white'); } });
$(document).on('keyup', '#R_3', function () { if (Number.parseFloat($('#R_3').val()) < Number.parseFloat($('#L_3').val())) { $('#3').css('borderColor', 'red'); } else { $('#3').css('borderColor', 'white'); } if (Number.parseFloat($('#R_4').val()) < Number.parseFloat($('#L_4').val())) { $('#4').css('borderColor', 'red'); } else { $('#4').css('borderColor', 'white'); } }); $(document).on('keyup', '#L_3', function () { if (Number.parseFloat($('#R_3').val()) < Number.parseFloat($('#L_3').val())) { $('#3').css('borderColor', 'red'); } else { $('#3').css('borderColor', 'white'); } if (Number.parseFloat($('#R_2').val()) < Number.parseFloat($('#L_2').val())) { $('#2').css('borderColor', 'red'); } else { $('#2').css('borderColor', 'white'); } });
$(document).on('keyup', '#R_4', function () { if (Number.parseFloat($('#R_4').val()) < Number.parseFloat($('#L_4').val())) { $('#4').css('borderColor', 'red'); } else { $('#4').css('borderColor', 'white'); } if (Number.parseFloat($('#R_5').val()) < Number.parseFloat($('#L_5').val())) { $('#5').css('borderColor', 'red'); } else { $('#5').css('borderColor', 'white'); } }); $(document).on('keyup', '#L_4', function () { if (Number.parseFloat($('#R_4').val()) < Number.parseFloat($('#L_4').val())) { $('#4').css('borderColor', 'red'); } else { $('#4').css('borderColor', 'white'); } if (Number.parseFloat($('#R_3').val()) < Number.parseFloat($('#L_3').val())) { $('#3').css('borderColor', 'red'); } else { $('#3').css('borderColor', 'white'); } });
$(document).on('keyup', '#R_5', function () { if (Number.parseFloat($('#R_5').val()) < Number.parseFloat($('#L_5').val())) { $('#5').css('borderColor', 'red'); } else { $('#5').css('borderColor', 'white'); } if (Number.parseFloat($('#R_6').val()) < Number.parseFloat($('#L_6').val())) { $('#6').css('borderColor', 'red'); } else { $('#6').css('borderColor', 'white'); } }); $(document).on('keyup', '#L_5', function () { if (Number.parseFloat($('#R_5').val()) < Number.parseFloat($('#L_5').val())) { $('#5').css('borderColor', 'red'); } else { $('#5').css('borderColor', 'white'); } if (Number.parseFloat($('#R_4').val()) < Number.parseFloat($('#L_4').val())) { $('#4').css('borderColor', 'red'); } else { $('#4').css('borderColor', 'white'); } });
$(document).on('keyup', '#R_6', function () { if (Number.parseFloat($('#R_6').val()) < Number.parseFloat($('#L_6').val())) { $('#6').css('borderColor', 'red'); } else { $('#6').css('borderColor', 'white'); } if (Number.parseFloat($('#R_7').val()) < Number.parseFloat($('#L_7').val())) { $('#7').css('borderColor', 'red'); } else { $('#7').css('borderColor', 'white'); } }); $(document).on('keyup', '#L_6', function () { if (Number.parseFloat($('#R_6').val()) < Number.parseFloat($('#L_6').val())) { $('#6').css('borderColor', 'red'); } else { $('#6').css('borderColor', 'white'); } if (Number.parseFloat($('#R_5').val()) < Number.parseFloat($('#L_5').val())) { $('#5').css('borderColor', 'red'); } else { $('#5').css('borderColor', 'white'); } });
$(document).on('keyup', '#R_7', function () { if (Number.parseFloat($('#R_7').val()) < Number.parseFloat($('#L_7').val())) { $('#7').css('borderColor', 'red'); } else { $('#7').css('borderColor', 'white'); } if (Number.parseFloat($('#R_8').val()) < Number.parseFloat($('#L_8').val())) { $('#8').css('borderColor', 'red'); } else { $('#8').css('borderColor', 'white'); } }); $(document).on('keyup', '#L_7', function () { if (Number.parseFloat($('#R_7').val()) < Number.parseFloat($('#L_7').val())) { $('#7').css('borderColor', 'red'); } else { $('#7').css('borderColor', 'white'); } if (Number.parseFloat($('#R_6').val()) < Number.parseFloat($('#L_6').val())) { $('#6').css('borderColor', 'red'); } else { $('#6').css('borderColor', 'white'); } });
$(document).on('keyup', '#R_8', function () { if (Number.parseFloat($('#R_8').val()) < Number.parseFloat($('#L_8').val())) { $('#8').css('borderColor', 'red'); } else { $('#8').css('borderColor', 'white'); } if (Number.parseFloat($('#R_9').val()) < Number.parseFloat($('#L_9').val())) { $('#9').css('borderColor', 'red'); } else { $('#9').css('borderColor', 'white'); } }); $(document).on('keyup', '#L_8', function () { if (Number.parseFloat($('#R_8').val()) < Number.parseFloat($('#L_8').val())) { $('#8').css('borderColor', 'red'); } else { $('#8').css('borderColor', 'white'); } if (Number.parseFloat($('#R_7').val()) < Number.parseFloat($('#L_7').val())) { $('#7').css('borderColor', 'red'); } else { $('#7').css('borderColor', 'white'); } });
$(document).on('keyup', '#R_9', function () { if (Number.parseFloat($('#R_9').val()) < Number.parseFloat($('#L_9').val())) { $('#9').css('borderColor', 'red'); } else { $('#9').css('borderColor', 'white'); } if (Number.parseFloat($('#R_10').val()) < Number.parseFloat($('#L_10').val())) { $('#10').css('borderColor', 'red'); } else { $('#10').css('borderColor', 'white'); } }); $(document).on('keyup', '#L_9', function () { if (Number.parseFloat($('#R_9').val()) < Number.parseFloat($('#L_9').val())) { $('#9').css('borderColor', 'red'); } else { $('#9').css('borderColor', 'white'); } if (Number.parseFloat($('#R_8').val()) < Number.parseFloat($('#L_8').val())) { $('#8').css('borderColor', 'red'); } else { $('#8').css('borderColor', 'white'); } });
$(document).on('keyup', '#R_10', function () { if (Number.parseFloat($('#R_10').val()) < Number.parseFloat($('#L_10').val())) { $('#10').css('borderColor', 'red'); } else { $('#10').css('borderColor', 'white'); } if (Number.parseFloat($('#R_11').val()) < Number.parseFloat($('#L_11').val())) { $('#11').css('borderColor', 'red'); } else { $('#11').css('borderColor', 'white'); } }); $(document).on('keyup', '#L_10', function () { if (Number.parseFloat($('#R_10').val()) < Number.parseFloat($('#L_10').val())) { $('#10').css('borderColor', 'red'); } else { $('#10').css('borderColor', 'white'); } if (Number.parseFloat($('#R_9').val()) < Number.parseFloat($('#L_9').val())) { $('#9').css('borderColor', 'red'); } else { $('#9').css('borderColor', 'white'); } });
$(document).on('keyup', '#R_11', function () { if (Number.parseFloat($('#R_11').val()) < Number.parseFloat($('#L_11').val())) { $('#11').css('borderColor', 'red'); } else { $('#11').css('borderColor', 'white'); } if (Number.parseFloat($('#R_12').val()) < Number.parseFloat($('#L_12').val())) { $('#12').css('borderColor', 'red'); } else { $('#12').css('borderColor', 'white'); } }); $(document).on('keyup', '#L_11', function () { if (Number.parseFloat($('#R_11').val()) < Number.parseFloat($('#L_11').val())) { $('#11').css('borderColor', 'red'); } else { $('#11').css('borderColor', 'white'); } if (Number.parseFloat($('#R_10').val()) < Number.parseFloat($('#L_10').val())) { $('#10').css('borderColor', 'red'); } else { $('#10').css('borderColor', 'white'); } });
$(document).on('keyup', '#R_12', function () { if (Number.parseFloat($('#R_12').val()) < Number.parseFloat($('#L_12').val())) { $('#12').css('borderColor', 'red'); } else { $('#12').css('borderColor', 'white'); } if (Number.parseFloat($('#R_13').val()) < Number.parseFloat($('#L_13').val())) { $('#13').css('borderColor', 'red'); } else { $('#13').css('borderColor', 'white'); } }); $(document).on('keyup', '#L_12', function () { if (Number.parseFloat($('#R_12').val()) < Number.parseFloat($('#L_12').val())) { $('#12').css('borderColor', 'red'); } else { $('#12').css('borderColor', 'white'); } if (Number.parseFloat($('#R_11').val()) < Number.parseFloat($('#L_11').val())) { $('#11').css('borderColor', 'red'); } else { $('#11').css('borderColor', 'white'); } });
$(document).on('keyup', '#R_13', function () { if (Number.parseFloat($('#R_13').val()) < Number.parseFloat($('#L_13').val())) { $('#13').css('borderColor', 'red'); } else { $('#13').css('borderColor', 'white'); } if (Number.parseFloat($('#R_14').val()) < Number.parseFloat($('#L_14').val())) { $('#14').css('borderColor', 'red'); } else { $('#14').css('borderColor', 'white'); } }); $(document).on('keyup', '#L_13', function () { if (Number.parseFloat($('#R_13').val()) < Number.parseFloat($('#L_13').val())) { $('#13').css('borderColor', 'red'); } else { $('#13').css('borderColor', 'white'); } if (Number.parseFloat($('#R_12').val()) < Number.parseFloat($('#L_12').val())) { $('#12').css('borderColor', 'red'); } else { $('#12').css('borderColor', 'white'); } });
$(document).on('keyup', '#R_14', function () { if (Number.parseFloat($('#R_14').val()) < Number.parseFloat($('#L_14').val())) { $('#14').css('borderColor', 'red'); } else { $('#14').css('borderColor', 'white'); } if (Number.parseFloat($('#R_15').val()) < Number.parseFloat($('#L_15').val())) { $('#15').css('borderColor', 'red'); } else { $('#15').css('borderColor', 'white'); } }); $(document).on('keyup', '#L_14', function () { if (Number.parseFloat($('#R_14').val()) < Number.parseFloat($('#L_14').val())) { $('#14').css('borderColor', 'red'); } else { $('#14').css('borderColor', 'white'); } if (Number.parseFloat($('#R_13').val()) < Number.parseFloat($('#L_13').val())) { $('#13').css('borderColor', 'red'); } else { $('#13').css('borderColor', 'white'); } });

$(document).on('keyup', '#S_1', function () { if (Number.parseFloat($('#S_1').val()) < 0) { $('#1').css('borderColor', 'red'); } else { $('#1').css('borderColor', 'white'); } }); 
$(document).on('keyup', '#S_2', function () { if (Number.parseFloat($('#S_2').val()) < 0) { $('#2').css('borderColor', 'red'); } else { $('#2').css('borderColor', 'white'); } }); 
$(document).on('keyup', '#S_3', function () { if (Number.parseFloat($('#S_3').val()) < 0) { $('#3').css('borderColor', 'red'); } else { $('#3').css('borderColor', 'white'); } }); 
$(document).on('keyup', '#S_4', function () { if (Number.parseFloat($('#S_4').val()) < 0) { $('#4').css('borderColor', 'red'); } else { $('#4').css('borderColor', 'white'); } }); 
$(document).on('keyup', '#S_5', function () { if (Number.parseFloat($('#S_5').val()) < 0) { $('#5').css('borderColor', 'red'); } else { $('#5').css('borderColor', 'white'); } }); 
$(document).on('keyup', '#S_6', function () { if (Number.parseFloat($('#S_6').val()) < 0) { $('#6').css('borderColor', 'red'); } else { $('#6').css('borderColor', 'white'); } }); 
$(document).on('keyup', '#S_7', function () { if (Number.parseFloat($('#S_7').val()) < 0) { $('#7').css('borderColor', 'red'); } else { $('#7').css('borderColor', 'white'); } }); 
$(document).on('keyup', '#S_8', function () { if (Number.parseFloat($('#S_8').val()) < 0) { $('#8').css('borderColor', 'red'); } else { $('#8').css('borderColor', 'white'); } }); 
$(document).on('keyup', '#S_9', function () { if (Number.parseFloat($('#S_9').val()) < 0) { $('#9').css('borderColor', 'red'); } else { $('#9').css('borderColor', 'white'); } }); 
$(document).on('keyup', '#S_10', function () { if (Number.parseFloat($('#S_10').val()) < 0) { $('#10').css('borderColor', 'red'); } else { $('#10').css('borderColor', 'white'); } });
$(document).on('keyup', '#S_11', function () { if (Number.parseFloat($('#S_11').val()) < 0) { $('#11').css('borderColor', 'red'); } else { $('#11').css('borderColor', 'white'); } });
$(document).on('keyup', '#S_12', function () { if (Number.parseFloat($('#S_12').val()) < 0) { $('#12').css('borderColor', 'red'); } else { $('#12').css('borderColor', 'white'); } });
$(document).on('keyup', '#S_13', function () { if (Number.parseFloat($('#S_13').val()) < 0) { $('#13').css('borderColor', 'red'); } else { $('#13').css('borderColor', 'white'); } });
$(document).on('keyup', '#S_14', function () { if (Number.parseFloat($('#S_14').val()) < 0) { $('#14').css('borderColor', 'red'); } else { $('#14').css('borderColor', 'white'); } });



